import React, { useState } from "react";
import { X, Copy, Check, FileText, Download } from "lucide-react";

const AUDIENCE_LABELS = {
  student: "School Student",
  junior: "Junior Developer",
  senior: "Senior Architect",
  pm: "Product Manager",
};

function generateMarkdown(auditData, selectedDistrict, audience) {
  const lines = [];

  lines.push("# 🛡️ RepoMap Sentinel — Onboarding Ticket");
  lines.push("");
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Audience:** ${AUDIENCE_LABELS[audience]}`);
  lines.push(`**Detected Architecture:** ${auditData.detectedArchitecture}`);
  lines.push(`**Technical Debt Grade:** ${auditData.technicalDebtGrade}`);
  lines.push("");

  // ── District Overview ──
  lines.push("## 📋 Architecture Districts");
  lines.push("");

  auditData.districts?.forEach((d, i) => {
    lines.push(`### ${i + 1}. ${d.name} (\`${d.layer}\`)`);
    lines.push("");
    const desc = d.descriptions?.[audience] || "No description available.";
    lines.push(`> ${desc}`);
    lines.push("");
    if (d.connectsTo && d.connectsTo.length > 0) {
      lines.push(`**Dependencies:** ${d.connectsTo.map((id) => `\`${id}\``).join(", ")}`);
      lines.push("");
    }
  });

  // ── Compliance Violations ──
  if (auditData.complianceViolations && auditData.complianceViolations.length > 0) {
    lines.push("## ⚠️ Compliance Violations");
    lines.push("");
    lines.push("| Severity | Issue | Remediation |");
    lines.push("|----------|-------|-------------|");

    auditData.complianceViolations.forEach((v) => {
      const sevEmoji =
        v.severity === "critical"
          ? "🔴"
          : v.severity === "high"
          ? "🟠"
          : v.severity === "medium"
          ? "🟡"
          : "🔵";
      lines.push(
        `| ${sevEmoji} ${v.severity.toUpperCase()} | ${v.issue} | ${v.remediation} |`
      );
    });
    lines.push("");
  }

  // ── Onboarding Checklist ──
  lines.push("## ✅ Onboarding Checklist");
  lines.push("");
  lines.push("- [ ] Review the architecture diagram above");
  lines.push("- [ ] Read each district description for your role");
  lines.push("- [ ] Understand the dependency flow between districts");
  lines.push("- [ ] Review all compliance violations and their remediations");
  lines.push("- [ ] Identify your primary working district(s)");
  lines.push("- [ ] Set up local development environment");
  lines.push("- [ ] Run existing test suites");
  lines.push("");
  lines.push("---");
  lines.push("*Generated by RepoMap Sentinel*");

  return lines.join("\n");
}

export default function TicketModal({
  auditData,
  selectedDistrict,
  audience,
  onClose,
}) {
  const [copied, setCopied] = useState(false);

  const markdown = generateMarkdown(auditData, selectedDistrict, audience);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = markdown;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sentinel-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const exportData = {
      generatedAt: new Date().toISOString(),
      audience,
      detectedArchitecture: auditData.detectedArchitecture,
      technicalDebtGrade: auditData.technicalDebtGrade,
      districts: auditData.districts,
      complianceViolations: auditData.complianceViolations,
      executionTraces: auditData.executionTraces,
    };
    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: "application/json;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sentinel-audit-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 backdrop-blur-sm animate-fade-in"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="w-[700px] max-h-[80vh] bg-panel border border-border rounded-2xl shadow-2xl flex flex-col animate-slide-up overflow-hidden">
        {/* ── Modal Header ── */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-accent" />
            <h2 className="text-sm font-semibold text-white">
              Onboarding Ticket
            </h2>
            <span className="text-[10px] font-mono text-zinc-500 px-2 py-0.5 rounded bg-canvas border border-border">
              GFM Markdown
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold
                         transition-all duration-200
                         ${
                           copied
                             ? "bg-accent/20 border border-accent/40 text-accent"
                             : "bg-canvas border border-border text-zinc-300 hover:border-accent/40 hover:text-accent"
                         }`}
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  Copy
                </>
              )}
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold
                         bg-canvas border border-border text-zinc-300
                         hover:border-sky-400/40 hover:text-sky-400 transition-all duration-200"
            >
              <Download className="w-3.5 h-3.5" />
              .md
            </button>
            <button
              onClick={handleDownloadJSON}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold
                         bg-canvas border border-border text-zinc-300
                         hover:border-amber-400/40 hover:text-amber-400 transition-all duration-200"
            >
              <Download className="w-3.5 h-3.5" />
              .json
            </button>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg flex items-center justify-center
                         text-zinc-500 hover:text-white hover:bg-zinc-800
                         transition-all duration-200"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* ── Markdown Content ── */}
        <div className="flex-1 overflow-y-auto p-6">
          <pre className="text-xs font-mono text-zinc-300 leading-relaxed whitespace-pre-wrap break-words">
            {markdown}
          </pre>
        </div>
      </div>
    </div>
  );
}

